# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-15 15:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usercourse',
            options={'verbose_name': '\u7528\u6237\u5b66\u4e60', 'verbose_name_plural': '\u7528\u6237\u5b66\u4e60'},
        ),
    ]
