# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-18 00:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_auto_20180117_2343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='learn_times',
        ),
    ]
