# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-14 23:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20171112_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='index',
            field=models.IntegerField(default=100, verbose_name='\u8f6e\u64ad\u56fe\u987a\u5e8f'),
        ),
    ]
